# Generated by Django 5.0.6 on 2024-10-12 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminside", "0005_alter_order_status_alter_order_tracking_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="tracking_number",
            field=models.CharField(
                default="EXWAf8a8a1fc-e610-4f9e-ORDER", max_length=30, unique=True
            ),
        ),
    ]
